Repository kin-kins/Web_Warriors-SOEN6011summer2023, pull requests merged in 2023-08, with the labels that each got.

#102 Updated jobs frontend #52
  .DS_Store
  templates/jobs.html
Labels: task

#105 Issue #50 - Select notification logic from the database for a user
  run.py
Labels: task

#106 Added notification functionality for job posts where candidates get notified
  app/__pycache__/activities_app.cpython-311.pyc
  app/__pycache__/booking_history.cpython-311.pyc
  app/__pycache__/flights_app.cpython-311.pyc
  app/__pycache__/hotels_app.cpython-311.pyc
  app/__pycache__/login_app.cpython-311.pyc
  app/__pycache__/package_app.cpython-311.pyc
  app/__pycache__/stripePayment.cpython-311.pyc
  app/__pycache__/trip_app.cpython-311.pyc
  app/jobs_posting.py
  app/resume.py
Labels: task, additional

#108 Updated UI layout #45
  .DS_Store
  templates/layout.html
Labels: enhancement, task

#111 new test modules added
  pytest_unit_test.py
Labels: additional
