Repository kin-kins/Web_Warriors-SOEN6011summer2023, pull requests merged in 2023-07, with the labels that each got.

#76 Issue #75 - Created the requirements.txt and Dockerfile for the environment
  Dockerfile
  requirements.txt
Labels: task

#78 Frontend features
  .DS_Store
  templates/booking-history.html
  templates/edit-user.html
  templates/resume.html
Labels: enhancement

#81 creating run.py and login api's
  run.py
Labels: task

#82 Adding the upload resume, post job applications, and apply to job post features (#12, #13, #35, #36, #57, #58)
  app/activities_app.py
  app/resume.py
Labels: task

#84 Added Login and Registration Feature (#18, #19)
  app/login_app.py
Labels: user story, task

#89 frontend updates for add jobs and layouts #37
  .DS_Store
  static/font/roboto/.Roboto-Thin 2.woff2.icloud
  static/fonts/roboto/.Roboto-Bold 2.eot.icloud
  static/fonts/roboto/.Roboto-Bold 2.ttf.icloud
  static/fonts/roboto/.Roboto-Bold 2.woff.icloud
  static/fonts/roboto/.Roboto-Bold 2.woff2.icloud
  static/fonts/roboto/.Roboto-Light 2.eot.icloud
  static/fonts/roboto/.Roboto-Light 2.ttf.icloud
  static/fonts/roboto/.Roboto-Light 2.woff.icloud
  static/fonts/roboto/.Roboto-Light 2.woff2.icloud
  static/fonts/roboto/.Roboto-Medium 2.eot.icloud
  static/fonts/roboto/.Roboto-Medium 2.ttf.icloud
  static/fonts/roboto/.Roboto-Medium 2.woff.icloud
  static/fonts/roboto/.Roboto-Medium 2.woff2.icloud
  static/fonts/roboto/.Roboto-Regular 2.eot.icloud
  static/fonts/roboto/.Roboto-Regular 2.ttf.icloud
  static/fonts/roboto/.Roboto-Regular 2.woff.icloud
  static/fonts/roboto/.Roboto-Regular 2.woff2.icloud
  static/fonts/roboto/.Roboto-Thin 2.eot.icloud
  static/fonts/roboto/.Roboto-Thin 2.ttf.icloud
  static/fonts/roboto/.Roboto-Thin 2.woff.icloud
  static/fonts/roboto/.Roboto-Thin 2.woff2.icloud
  templates/add_activity.html
  templates/index.html
  templates/jobs.html
  templates/layout.html
  templates/review_candidate.html
Labels: task

#92 Updated login, added functionality for employers to be able to login
  app/login_app.py
Labels: user story, task

#91 Updated Activity and Customer
  src/activity.py
  src/customer.py
Labels: task

#93 Updated functionality for job tracking
  app/jobs_posting.py
  app/resume.py
Labels: task

#96 Issue #48 - Added candidate selection and rejection mechanism
  run.py
Labels: task

#98 updated resume #15
  templates/resume.html
Labels: enhancement, task

#99 adding test and resolving the following issues
  app/applied_jobs.py
  app/jobs_posting.py
  app/login_app.py
  pytest_unit_test.py
  templates/.DS_Store
  templates/applied_jobs.html
  templates/jobs.html
  templates/layout.html
  templates/login.html
  templates/review_candidate.html
Labels: enhancement, epic, user story, task
